name: CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main


defaults:
  run:
    working-directory: server


jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vybe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Typecheck backend
        run: npm run typecheck

      - name: Build backend
        run: npm run build

      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Build frontend
        working-directory: client
        # Set dummy env so it build successfully in CI. The actual env will be set in the deployment.
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8080
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          NEXT_PUBLIC_WS_URL: ws://localhost:8080
        run: npm run build

  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vybe:backend-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vybe:backend-${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_WS_URL=${{ vars.NEXT_PUBLIC_WS_URL }}
            NEXT_PUBLIC_APP_URL=${{ vars.NEXT_PUBLIC_APP_URL }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vybe:frontend-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vybe:frontend-${{ github.sha }}